name: favos
description: “This app is a specialized note-taking application that allows you to consolidate and manage all your favorite spots, including a wide range of shops and facilities, not just restaurants. When you discover a new place, you can save its details. Additionally, you can jot down your impressions and recommendations for any shop or facility you’ve visited. This app is your personal guide to exploring and remembering the places you love.”

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  intl: any
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  flutter_native_splash: ^2.4.0
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
